test_average (__main__.TestExercice) ... ok
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 95, in test_to_celsius
    self.assertListEqual(
AssertionError: Lists differ: [-32.0, -45.888888888888886, 218.55555555555554] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 0:
-32.0
-17.77777777777778

- [-32.0, -45.888888888888886, 218.55555555555554]
+ [-17.77777777777778, -31.666666666666664, 232.77777777777777] : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 83, in test_to_degrees
    self.assertListEqual(
AssertionError: Lists differ: [(114, 35.493541569878744, 29.6124941927246[139 chars]998)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114, 35.493541569878744, 29.612494192724625)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114, 35.493541569878744, 29.612494192724625),
-  (-230, 49.01291686024251, 0.7750116145507491),
-  (286, 28.73385392469686, 44.031235481811564),
-  (234, 20.384292510402133, 23.057550624127998)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

======================================================================
FAIL: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 64, in test_to_radians
    self.assertListEqual(
AssertionError: Lists differ: [(-0.08726646259971647, 0.0349065850398865[193 chars]978)] != [-0.08668468618238503, 0.17598251810595048[32 chars]2748]

First differing element 0:
(-0.08726646259971647, 0.03490658503988659, 0.0)
-0.08668468618238503

+ [-0.08668468618238503, 0.17598251810595048, 6.283490739798685, 6.9973449482748]
- [(-0.08726646259971647, 0.03490658503988659, 0.0),
-  (0.17453292519943295, 0.06981317007977318, 1.0297442586766545),
-  (6.283185307179586, 0.017453292519943295, 0.05235987755982989),
-  (6.981317007977318, 0.9599310885968813, 0.10471975511965978)] : Mauvais calcul de degres -> radians

----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (failures=3)
